# Generated by Django 5.2.17 on 2026-09-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_points",
                    models.IntegerField(
                        default=10, help_text="Points awarded for a correct sign."
                    ),
                ),
                (
                    "incorrect_points",
                    models.IntegerField(
                        default=-5,
                        help_text="Points awarded (usually negative) for an incorrect sign.",
                    ),
                ),
                (
                    "min_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Minimum model confidence (0-1) required to accept a prediction as correct. 0 disables this check.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Practice Settings",
                "verbose_name_plural": "Practice Settings",
            },
        ),
    ]
