# Generated by Django 5.2.17 on 2026-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("alphabet", "Alphabet"), ("basic", "Basic Sign")],
                        max_length=20,
                    ),
                ),
                ("letter", models.CharField(blank=True, max_length=1, null=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="signs/")),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="sign_videos/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
